### ISSUE TITLE
Question about clear timeout

### ISSUE THREAD

**Issue by gou4shi1** [vitalets/await-timeout#12]
Hello, I have a small quesiton about this code:
 ```js
 import Timeout from 'await-timeout';

 const timer = new Timeout();
 try {
   await Promise.race([
     fetch('https://example.com'),
     timer.set(1000, 'Timeout!')
   ]);
 } finally {
   timer.clear();
 }
 ```
> Without a timer cleanup you may get unexpected effects in you code - as all promises in `Promise.race` are get fulfille
   
Why the timer need to be cleanup? `race()` only accept the first settled promise.

**Comment by vitalets** [comment]
Imagine you have the following code:
```js
const timer = new Timeout();
try {
  await Promise.race([
    fetch('https://example.com'),
    timer.set(1000).then(() => {
       console.log('Operation timeout');
       throw new Error('Timeout'); 
    });
  ]);
} finally {
  timer.clear();
}
```
Even if fetch resolve first, we will get `Operation timeout` in console.

PS: in modern Node.js env there is [built-in timers API](https://nodejs.org/api/timers.html#timers-promises-api) with the same functionality.
