### ISSUE TITLE
Unexpected token: operator (>) - add ES5 build

### ISSUE THREAD

**Issue by yuu2lee4** [vitalets/await-timeout#5]
report by UglifyJs

**Comment by vitalets** [comment]
This is because UglifyJs does not support ES6 arrow functions (=>). 
Do you use arrow functions in your project?
If you are using webpack, you can update `uglifyjs-webpack-plugin` or use `terser-webpack-plugin`
Here [the discussion on Stackoverflow](https://stackoverflow.com/questions/43888474/unexpected-token-operator-from-uglifyjs).

**Comment by yuu2lee4** [comment]
yeah,i use some es6 feature,but i have babel to transform it except the packages installed under node_modules

**Comment by vitalets** [comment]
Oh, sure. I will make a es5 build along with es6.

**Comment by vitalets** [comment]
I've released 0.6.0 with ES5 support.
Please try 
```js
import Timeout from 'await-timeout/es5';
```

**Comment by yuu2lee4** [comment]
maybe using pkg.main  and pkg. module to import ?

**Comment by vitalets** [comment]
> maybe using pkg.main and pkg. module to import ?

For me such approach has one disadvantage: all developers who uses ES6 but does not use modules will get ES5 version of library.

**Comment by yuu2lee4** [comment]
1.0.1 has no es5 build?

**Comment by vitalets** [comment]
> 1.0.1 has no es5 build?

I've returned it in 1.1.0: 
```js
const Timeout = require('await-timeout/es5');
```
But in general I think more and more libraries will tend to be published without es5 version.
There are several reasons:
1. it's better for project itself to define which environments is supports and transpile only needed things -> less bundle size
2. when transpiling/bundling inside project helper functions not inserted in every library you use  -> also less bundle size 

[There is a long thread on that](https://github.com/sindresorhus/ama/issues/446)
